
CODES = {
    200: "TR-",  # 'thunderstorm with light rain',
    201: "TR",  #'thunderstorm with rain',
    202: "tr+",  #'thunderstorm with heavy rain',
    210: "t-",  #'light thunderstorm',
    211: "t",  #'thunderstorm',
    212: "t+",  #'heavy thunderstorm',
    221: "t!",  #'ragged thunderstorm',
    230: 'thunderstorm with light drizzle',
    231: 'thunderstorm with drizzle',
    232: 'thunderstorm with heavy drizzle',
 
    300: 'D-', #'light intensity drizzle',
    301: 'drizzle',
    302: 'heavy intensity drizzle',
    310: 'light intensity drizzle rain',
    311: 'drizzle rain',
    312: 'heavy intensity drizzle rain',
    313: 'shower rain and drizzle',
    314: 'heavy shower rain and drizzle',
    321: 'shower drizzle',
 
    500: "R-",  #'light rain',
    501: "R",  #'moderate rain',
    502: "R+",  #'heavy intensity rain',
    503: "R++",  #'very heavy rain',
    504: "R!",  #'extreme rain',
    511: 'freezing rain',
    520: 'light intensity shower rain',
    521: 'shower rain',
    522: 'heavy intensity shower rain',
    531: 'ragged shower rain',
 
    600: 'S-', #light snow',
    601: 'S', #snow',
    602: 'S+', #heavy snow',
    611: 'sleet',
    612: 'shower sleet',
    615: 'light rain and snow ',
    616: 'rain and snow ',
    620: 'light shower snow',
    621: 'shower snow',
    622: 'heavy shower snow',
 
    701: 'mist',
    711: 'smoke',
    721: 'haze',
    731: 'Sand/Dust Whirls',
    741: 'Fog',
    751: 'sand',
    761: 'dust',
    762: 'VOLCANIC ASH',
    771: 'SQUALLS',
    781: 'TORNADO ',
 
    800: "C0",  #'sky is clear',
    801: "C-",  #'few clouds',
    802: "C",  #'scattered clouds',
    803: "C+",  #'broken clouds',
    804: "C!",  #'overcast clouds',
}